In [73]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.common.exceptions import ElementNotInteractableException
#Importing requests
import requests

# importing regex
import re

In [181]:
PATH = 'C:\Program Files (x86)\chromedriver.exe'                          
driver = webdriver.Chrome(r"C:\\Users\\hp\\Downloads\\chromedriver_win32\\chromedriver.exe")

<ipython-input-181-b5d72fea875f>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\\Users\\hp\\Downloads\\chromedriver_win32\\chromedriver.exe")

Q1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [3]:
#website url
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [43]:
#creating variables
rank=[]
name=[]
artist=[]
views=[]
dou=[]

# fetching rank
try:
    rank_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
    for i in rank_tag:
        ranks=i.text
        rank.append(ranks)
except NoSuchElementException:
    rank.append('-')
    
#fetching Name
try:
    name_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
    for i in name_tag:
        names=i.text
        name.append(names)
except NoSuchElementException:
    name.append('-')
    
#fetching Artist:
try:
    artist_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
    for i in artist_tag:
        artists=i.text
        artist.append(artists)
except NoSuchElementException:
    artist.append('-')
    
#fetching Views:
try:
    view_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
    for i in view_tag:
        view=i.text
        views.append(view)
except NoSuchElementException:
    views.append('-')
    
#fetching Name
try:
    dou_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
    for i in dou_tag:
        dous=i.text
        dou.append(dous)
except NoSuchElementException:
    dou.append('-')

#creating dataframe:
df=pd.DataFrame({"Rank": rank[0:180:6],"Name": name[1:180:6],"Artist": artist[2:180:6],"Views": views[3:180:6],"Date of Uploaded": dou[4:180:6]})

<ipython-input-43-381b80e0cf9a>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  rank_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
<ipython-input-43-381b80e0cf9a>:18: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
<ipython-input-43-381b80e0cf9a>:26: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  artist_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
<ipython-input-43-381b80e0cf9a>:34: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  view_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")
<ipython-input-43-381b80e0cf9a>:42: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  dou_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td")

In [44]:
df

,Rank,Name,Artist,Views,Date of Uploaded
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,9.85,"June 17, 2016"
1,2.,"""Despacito""[5]",Luis Fonsi,7.66,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[11]",LooLoo Kids,6.01,"October 8, 2016"
3,4.,"""Shape of You""[12]",Ed Sheeran,5.56,"January 30, 2017"
4,5.,"""See You Again""[14]",Wiz Khalifa,5.36,"April 6, 2015"
5,6.,"""Bath Song""[19]",Cocomelon – Nursery Rhymes,4.74,"May 2, 2018"
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[20]",Miroshka TV,4.54,"February 27, 2018"
7,8.,"""Masha and the Bear – Recipe for Disaster""[21]",Get Movies,4.47,"January 31, 2012"
8,9.,"""Uptown Funk""[22]",Mark Ronson,4.39,"November 19, 2014"
9,10.,"""Phonics Song with Two Words""[23]",ChuChu TV,4.35,"March 6, 2014"
10,11.,"""Gangnam Style""[24]",Psy,4.28,"July 15, 2012"
11,12.,"""Dame Tu Cosita""[29]",El Chombo,3.76,"April 5, 2018"
12,13.,"""Sugar""[30]",Maroon 5,3.61,"January 14, 2015"
13,14.,"""Sorry""[31]",Justin Bieber,3.49,"October 22, 2015"
14,15.,"""Roar""[32]",Katy Perry,3.49,"September 5, 2013"
15,16.,"""Counting Stars""[33]",OneRepublic,3.46,"May 31, 2013"
16,17.,"""Wheels on the Bus""[34]",Cocomelon – Nursery Rhymes,3.41,"May 24, 2018"
17,18.,"""Thinking Out Loud""[35]",Ed Sheeran,3.37,"October 7, 2014"
18,19.,"""Faded""[36]",Alan Walker,3.20,"December 3, 2015"
19,20.,"""Girls Like You""[37]",Maroon 5,3.20,"May 31, 2018"
20,21.,"""Dark Horse""[38]",Katy Perry,3.19,"February 20, 2014"
21,22.,"""Bailando""[39]",Enrique Iglesias,3.14,"April 11, 2014"
22,23.,"""Lean On""[40]",Major Lazer,3.13,"March 22, 2015"
23,24.,"""Let Her Go""[41]",Passenger,3.13,"July 25, 2012"
24,25.,"""Axel F""[42]",Crazy Frog,3.13,"June 16, 2009"
25,26.,"""Shake It Off""[43]",Taylor Swift,3.12,"August 18, 2014"
26,27.,"""Perfect""[44]",Ed Sheeran,3.04,"November 9, 2017"
27,28.,"""Mi Gente""[45]",J Balvin,3.01,"June 29, 2017"
28,29.,"""Waka Waka (This Time for Africa)""[46]",Shakira,3.01,"June 4, 2010"
29,30.,"""Baa Baa Black Sheep""[47]",Cocomelon – Nursery Rhymes,2.97,"June 25, 2018"

Q2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [81]:
#website url
driver.get("https://www.bcci.tv/")

In [82]:
time.sleep(2)
from selenium.common.exceptions import ElementNotInteractableException  #library imported

#fetching international fixtue webpage:
try:
    searching=driver.find_element_by_xpath("//li[@class='nav-item ml-0']/a")
    searching.click()
except ElementNotInteractableException as e:
    print("fail",e)
    driver.get("https://www.bcci.tv/international/fixtures")

<ipython-input-82-f55d3878249e>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  searching=driver.find_element_by_xpath("//li[@class='nav-item ml-0']/a")

In [94]:
#creating variables:
Match_title=[]
Series=[]
Place=[]
Date=[]
Time=[]

# Extracting Match_title
time.sleep(1)
try:
    Match=driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
    for i in Match:
        Matchs=i.text.split(' ')[0]
        Match_title.append(Matchs)
    Match_title[0:]
except NoSuchElementException:
    Match_title.append('-')
    
# Extracting Series
try:
    series=driver.find_elements_by_xpath("//span[@class='ng-binding']")
    for i in series:
        seriesn=i.text
        Series.append(seriesn)
    Series[0:]
except NoSuchElementException:
    Series.append("-")    
time.sleep(1)

# Extracting Place
try:
    place  = driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
    for i in place:
        places=i.text.split('-')[1:]
        Place.append(places)
    Place[0:]
except NoSuchElementException:
    Place.append("-")    
time.sleep(1)

# Extracting Date
try:
    date = driver.find_elements_by_xpath("//h5[@class='ng-binding']")  
    for i in date:
        dates=i.text
        Date.append(dates)
    Date[0:]
except NoSuchElementException:
    Date.append("-")  
time.sleep(1)

# Extracting Time
try:
    times_tag = driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")  
    for i in times_tag:
        times=i.text
        Time.append(times)
    Time[0:]
except NoSuchElementException:
    Time.append("-")  
time.sleep(1)

#creating dataframe
df=pd.DataFrame({'Match title':Match_title,
                'Series':Series,
                'Place':Place,
                'Date':Date,
                'Time':Time})

<ipython-input-94-df32b62446af>:11: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Match=driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
<ipython-input-94-df32b62446af>:20: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  series=driver.find_elements_by_xpath("//span[@class='ng-binding']")
<ipython-input-94-df32b62446af>:31: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  place  = driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
<ipython-input-94-df32b62446af>:42: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  date = driver.find_elements_by_xpath("//h5[@class='ng-binding']")
<ipython-input-94-df32b62446af>:53: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  times_tag = driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")

In [95]:
df

,Match title,Series,Place,Date,Time
0,2nd,INDIA TOUR OF SOUTH AFRICA TEST SERIES 2021-22,"[ The Wanderers Stadium, Johannesburg]",3 JAN 2022,1:30 PM IST
1,3rd,INDIA TOUR OF SOUTH AFRICA TEST SERIES 2021-22,"[ Newlands, Cape Town]",11 JAN 2022,2:00 PM IST
2,1st,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"[ Boland Park, Paarl]",19 JAN 2022,2:00 PM IST
3,2nd,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"[ Boland Park, Paarl]",21 JAN 2022,2:00 PM IST
4,3rd,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"[ Newlands, Cape Town]",23 JAN 2022,2:00 PM IST

Q3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [178]:
#website url
driver.get("https://www.guru99.com/")

In [149]:
# clicking selenium webpage 
selenium_u=driver.find_element_by_xpath("//a[@data-lasso-id='145318']")
selenium_u.click()

time.sleep(2)

selenium_v=driver.find_element_by_xpath("//a[@data-lasso-id='182688']")
selenium_v.click()

time.sleep(2)

name=[]
description=[]

#extracting name:
try:
    nametag=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td")
    for i in nametag:
        nt=i.text
        name.append(nt)
    name[0:81]
except NoSuchElementException:
    name.append('-')

time.sleep(1)

#extracting description:
try:
    desctag=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td")
    for i in desctag:
        desc_t=i.text
        description.append(desc_t)
    description[0:81]
except NoSuchElementException:
    description.append('-')

time.sleep(1)
print(len(name),len(description))  #checking length

#creating dataframe:
gurudf= pd.DataFrame({'Name':name[0:81:2],
                'Description':description[1:82:2]})

<ipython-input-149-a9a4fbe6b67e>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  selenium_u=driver.find_element_by_xpath("//a[@data-lasso-id='145318']")
<ipython-input-149-a9a4fbe6b67e>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  selenium_v=driver.find_element_by_xpath("//a[@data-lasso-id='182688']")
<ipython-input-149-a9a4fbe6b67e>:17: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  nametag=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td")
<ipython-input-149-a9a4fbe6b67e>:29: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  desctag=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td")

82 82

In [150]:
gurudf

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

Q4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP
D) GSDP
E) Share
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [149]:
#website url
driver.get("https://www.statisticstimes.com/")

In [150]:
#clicking on economy tab
eco_button=driver.find_element_by_xpath("//div[@class='navbar']/div[2]")
eco_button.click()

<ipython-input-150-1375359e2999>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  eco_button=driver.find_element_by_xpath("//div[@class='navbar']/div[2]")

In [151]:
#clicking on India
ec_button=driver.find_element_by_xpath("//div[@id='top']/div[2]/div[2]/div/a[3]")
ec_button.click()

<ipython-input-151-6e5bcdd84e63>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  ec_button=driver.find_element_by_xpath("//div[@id='top']/div[2]/div[2]/div/a[3]")

In [152]:
#clicking on Indian states by GDP for fetching data

try:
    adss=driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li[1]/a")
    adss.click()
except ElementNotInteractableException as e:
    print(e)

<ipython-input-152-6f090bb00eac>:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  adss=driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li[1]/a")

In [212]:
#creating variables

rank=[]
state=[]
gsdpC19_20=[]
gsdpC18_19=[]
gsdpO19_20=[]
gsdpO18_19=[]
share=[]
gdp=[]
time.sleep(1)

# Extracting rank
time.sleep(1)
try:
    rank_t=driver.find_elements_by_xpath("//tr[@role='row']/td[1]")
    for i in rank_t:
        ranks=i.text
        rank.append(ranks)
    rank[0:32]
except NoSuchElementException:
    rank.append('-')
    
# Extracting State
try:
    state_t=driver.find_elements_by_xpath("//tr[@role='row']/td[2]")
    for i in state_t:
        states=i.text
        state.append(states)
    state[0:32]
except NoSuchElementException:
    state.append("-")    
time.sleep(1)

# Extracting gsdp at Current price :2019-2020
try:
    gsdp1_t  = driver.find_elements_by_xpath("//tr[@role='row']/td[3]")
    for i in gsdp1_t:
        gsdp1=i.text
        gsdpC19_20.append(gsdp1)
    gsdpC19_20[0:32]
except NoSuchElementException:
    gsdpC19_20.append("-")    
time.sleep(1)

# Extracting gsdp at Current price :2018-2019
try:
    gsdp2_t = driver.find_elements_by_xpath("//tr[@role='row']/td[4]")  
    for i in gsdp2_t:
        gsdp2=i.text
        gsdpC18_19.append(gsdp2)
    gsdpC18_19[0:32]
except NoSuchElementException:
    gsdpC18_19.append("-")  
time.sleep(1)

# Extracting gsdp at Old price of 2011-12 :2019-2020
try:
    gsdp3_t = driver.find_elements_by_xpath("//tr[@role='row']/td[7]")  
    for i in gsdp3_t:
        gsdp3=i.text
        gsdpO19_20.append(gsdp3)
    gsdpO19_20[0:32]
except NoSuchElementException:
    gsdpO19_20.append("-")  
time.sleep(1)

#Extracting gsdp at Old price of 2011-12 :2018-2019

try:
    gsdp4_t  = driver.find_elements_by_xpath("//tr[@role='row']/td[8]")
    for i in gsdp4_t:
        gsdp4=i.text
        gsdpO18_19.append(gsdp4)
    gsdpO18_19[0:32]
except NoSuchElementException:
    gsdpO18_19.append("-")    
time.sleep(1)

# Extracting share
try:
    share_t = driver.find_elements_by_xpath("//tr[@role='row']/td[5]")  
    for i in share_t:
        shares=i.text
        share.append(shares)
    share[0:32]
except NoSuchElementException:
    share.append("-")  
time.sleep(1)

# Extracting GDP:
try:
    gdp_tag = driver.find_elements_by_xpath("//tr[@role='row']/td[6]")  
    for i in gdp_tag:
        gdps=i.text
        gdp.append(gdps)
    gdp[0:32]
except NoSuchElementException:
    gdp.append("-")  
time.sleep(1)

#creating dataframe
statsdf=pd.DataFrame({'Rank':rank[0:32],
                'State':state[0:32],
                'GSDP C 19_20':gsdpC19_20[0:32],
                'GSDP C 18_19':gsdpC18_19[0:32],
                'GSDP O 19_20':gsdpO19_20[0:32],
                'GSDP O 18_19':gsdpO18_19[0:32],
                'Share':share[0:32],
                'GDP':gdp[0:32]})

<ipython-input-212-2d3f726b6403>:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  rank_t=driver.find_elements_by_xpath("//tr[@role='row']/td[1]")
<ipython-input-212-2d3f726b6403>:24: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  state_t=driver.find_elements_by_xpath("//tr[@role='row']/td[2]")
<ipython-input-212-2d3f726b6403>:35: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  gsdp1_t  = driver.find_elements_by_xpath("//tr[@role='row']/td[3]")
<ipython-input-212-2d3f726b6403>:46: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  gsdp2_t = driver.find_elements_by_xpath("//tr[@role='row']/td[4]")
<ipython-input-212-2d3f726b6403>:57: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  gsdp3_t = driver.find_elements_by_xpath("//tr[@role='row']/td[7]")
<ipython-input-212-2d3f726b6403>:69: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  gsdp4_t  = driver.find_elements_by_xpath("//tr[@role='row']/td[8]")
<ipython-input-212-2d3f726b6403>:80: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  share_t = driver.find_elements_by_xpath("//tr[@role='row']/td[5]")
<ipython-input-212-2d3f726b6403>:91: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  gdp_tag = driver.find_elements_by_xpath("//tr[@role='row']/td[6]")

In [213]:
statsdf

,Rank,State,GSDP C 19_20,GSDP C 18_19,GSDP O 19_20,GSDP O 18_19,Share,GDP
0,1,Maharashtra,-,"2,632,792",-,"2,039,074",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208","1,312,929","1,215,307",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764","1,166,817","1,123,982",8.39%,240.726
3,4,Gujarat,-,"1,502,899",-,"1,186,379",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127","1,156,039","1,091,077",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898","793,223","739,525",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586","711,627","677,428",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957","672,018","621,301",4.57%,131.083
8,9,Telangana,"969,604","861,031","663,258","612,828",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592","561,801","522,009",4.29%,122.977
10,11,Kerala,-,"781,653",-,"559,412",4.14%,118.733
11,12,Delhi,"856,112","774,870","634,408","590,569",4.10%,117.703
12,13,Haryana,"831,610","734,163","572,240","531,085",3.89%,111.519
13,14,Bihar,"611,804","530,363","414,977","375,651",2.81%,80.562
14,15,Punjab,"574,760","526,376","418,868","397,669",2.79%,79.957
15,16,Odisha,"521,275","487,805","396,499","376,877",2.58%,74.098
16,17,Assam,-,"315,881",-,"234,048",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063","243,477","231,182",1.61%,46.187
18,19,Jharkhand,"328,598","297,204","240,036","224,986",1.57%,45.145
19,20,Uttarakhand,-,"245,895",-,"193,273",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",-,"112,755",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845","124,403","117,851",0.81%,23.369
22,23,Goa,"80,449","73,170","63,408","57,787",0.39%,11.115
23,24,Tripura,"55,984","49,845","40,583","36,963",0.26%,7.571
24,25,Chandigarh,-,"42,114",-,"31,192",0.22%,6.397
25,26,Puducherry,"38,253","34,433","25,093","23,013",0.18%,5.230
26,27,Meghalaya,"36,572","33,481","26,695","24,682",0.18%,5.086
27,28,Sikkim,"32,496","28,723","20,017","18,722",0.15%,4.363
28,29,Manipur,"31,790","27,870","20,673","19,300",0.15%,4.233
29,30,Nagaland,-,"27,283",-,"17,647",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",-,"16,676",0.13%,3.737
31,32,Mizoram,"26,503","22,287","18,797","16,478",0.12%,3.385

Q5.Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [21]:
#website url
driver.get("https://github.com/")

In [22]:
time.sleep(2)
from selenium.common.exceptions import ElementNotInteractableException   #importing library

#clicking on trending option in github homepage
try:
    searchings=driver.find_element_by_xpath("//summary[@class='HeaderMenu-summary HeaderMenu-link px-0 py-3 border-0 no-wrap d-block d-lg-inline-block']")
    searchings.click()
    time.sleep(1)
    searchingaa=driver.find_element_by_xpath("//a[@data-hydro-click-hmac='1fb8d24b3f56e88b54b3960d9b891606390c2cdd7c63eda8e31c1741c1b0c931']")
    searchingaa.click()
except ElementNotInteractableException as e:
    print("fail")
    driver.get("https://github.com/trending")

<ipython-input-22-cc2f5ac75f95>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  searchings=driver.find_element_by_xpath("//summary[@class='HeaderMenu-summary HeaderMenu-link px-0 py-3 border-0 no-wrap d-block d-lg-inline-block']")
<ipython-input-22-cc2f5ac75f95>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  searchingaa=driver.find_element_by_xpath("//a[@data-hydro-click-hmac='1fb8d24b3f56e88b54b3960d9b891606390c2cdd7c63eda8e31c1741c1b0c931']")

fail

In [23]:
#fetching url link of each element
urls=[]
for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
    urls.append(i.get_attribute("href"))

<ipython-input-23-762e791e3e05>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):

In [62]:
#defining variables
Repository_title=[]
Repository_description=[]
Contributors_count=[]
Language_used=[]


#scrapping the required details
for i in urls:
    driver.get(i)
    time.sleep(3)
        
    #fetching Repository_title:
    try:
        rep_t=driver.find_element_by_xpath("//strong[@class='mr-2 flex-self-stretch']/a") 
        Repository_title.append(rep_t.text)
    except NoSuchElementException:
        Repository_title.append('-')
    
    #fetching Repository_title:
    try:
        rep_d=driver.find_element_by_xpath("//p[@class='f4 my-3']") 
        Repository_description.append(rep_d.text)
    except NoSuchElementException:
        Repository_description.append('-')
    
    #fetching Repository_title:
    try:
        count_c=driver.find_element_by_xpath("//div[@id='repo-content-pjax-container']/div/div[2]/div[2]/div/div[3]/div/h2/a/span") 
        Contributors_count.append(count_c.text)
    except NoSuchElementException:
        Contributors_count.append('-')
        
    #fetching Language_used:
    try:
        lang_u=driver.find_element_by_xpath("//li[@class='d-inline']") 
        Language_used.append(lang_u.text.replace('\n', ' :'))
    except NoSuchElementException:
        Language_used.append('-')
        
#creating dataframe:        
gitdf=pd.DataFrame({'Repository title':Repository_title,
                'Repository description':Repository_description,
                'Contributors count':Contributors_count,
                'Language used':Language_used})

<ipython-input-62-2ab6dcfa5434>:15: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  rep_t=driver.find_element_by_xpath("//strong[@class='mr-2 flex-self-stretch']/a")
<ipython-input-62-2ab6dcfa5434>:22: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  rep_d=driver.find_element_by_xpath("//p[@class='f4 my-3']")
<ipython-input-62-2ab6dcfa5434>:29: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  count_c=driver.find_element_by_xpath("//div[@id='repo-content-pjax-container']/div/div[2]/div[2]/div/div[3]/div/h2/a/span")
<ipython-input-62-2ab6dcfa5434>:36: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  lang_u=driver.find_element_by_xpath("//li[@class='d-inline']")

In [63]:
gitdf

,Repository title,Repository description,Contributors count,Language used
0,MockingBird,🚀AI拟声: 5秒内克隆您的声音并生成任意语音内容 Clone a voice in 5 s...,-,JavaScript :62.1%
1,maven-mvnd,Apache Maven Daemon,,Java :94.0%
2,system-design-primer,Learn how to design large-scale systems. Prep ...,,Python :98.0%
3,sealos,一条命令离线安装高可用kubernetes，3min装完，500M，100年证书，版本不要太...,,Go :95.2%
4,python-cheatsheet,Comprehensive Python Cheatsheet,11,Python :50.5%
5,awesome,😎 Awesome lists about all kinds of interesting...,-,-
6,WV-AMZN-4K-RIPPER,"Tool To download Amazon 4k SDR HDR 1080, CDM I...",,Python :90.4%
7,crater,Open Source Invoicing Solution for Individuals...,,PHP :49.4%
8,marktext,"📝A simple and elegant markdown editor, availab...",-,JavaScript :75.9%
9,GoodbyeDPI,GoodbyeDPI—Passive Deep Packet Inspection bloc...,,C :99.1%
10,WELA,WELA (Windows Event Log Analyzer): The Swiss A...,,PowerShell :100.0%
11,minos2,Minos2 is a micro-kernel OS for ARMv8-a,,C :87.0%
12,svox2,Plenoxels: Radiance Fields without Neural Netw...,,Python :63.3%
13,light-show,Tesla Light Show,,Python :100.0%
14,spider-flow,新一代爬虫平台，以图形化方式定义爬虫流程，不写代码即可完成爬虫。,,Java :99.4%
15,bevy,A refreshingly simple data-driven game engine ...,-,Rust :99.9%
16,javascript-algorithms,📝 Algorithms and data structures implemented i...,-,JavaScript :100.0%
17,build-your-own-x,🤓 Build your own (insert technology here),,-
18,ja-netfilter,A javaagent framework,,Java :100.0%
19,awesome-selfhosted,A list of Free Software network services and w...,,JavaScript :57.3%
20,misbrands,The world's most hated IT stickers,-,-
21,token-list,The community maintained Solana token registry,,Go :74.1%
22,leetcode-master,LeetCode 刷题攻略：200道经典题目刷题顺序，共60w字的详细图解，视频难点剖析，5...,,-
23,GitHubDaily,GitHubDaily 分享内容定期整理与分类。欢迎推荐、自荐项目，让更多人知道你的项目。,,-
24,30-seconds-of-code,Short JavaScript code snippets for all your de...,264,JavaScript :100.0%

Q6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [182]:
#website url
driver.get("https://www.billboard.com/")

In [183]:
#clicking on side button for dropdown
try:
    search_c=driver.find_element_by_xpath("//button[@class='o-icon-button lrv-a-unstyle-button lrv-a-unstyle-link lrv-u-cursor-pointer lrv-u-flex js-MegaMenu-Trigger lrv-u-color-grey:hover lrv-a-hover-effect']")
    search_c.click()
except ElementNotInteractableException as e:
     print("Exception raised",e)

#clicking on charts:
try:
    search_charts=driver.find_element_by_xpath("//h3[@id='mega-menu-item-charts']/a")
    search_charts.click()
except ElementNotInteractableException as e:
    print("Exception raised",e)

<ipython-input-183-b1ecfbe3c8d3>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_c=driver.find_element_by_xpath("//button[@class='o-icon-button lrv-a-unstyle-button lrv-a-unstyle-link lrv-u-cursor-pointer lrv-u-flex js-MegaMenu-Trigger lrv-u-color-grey:hover lrv-a-hover-effect']")

Exception raised Message: element not interactable
  (Session info: chrome=96.0.4664.110)
Stacktrace:
Backtrace:
	Ordinal0 [0x006606F3+2492147]
	Ordinal0 [0x005F9BD1+2071505]
	Ordinal0 [0x00502340+1057600]
	Ordinal0 [0x0052D7D4+1234900]
	Ordinal0 [0x00523647+1193543]
	Ordinal0 [0x005457C3+1333187]
	Ordinal0 [0x00523466+1193062]
	Ordinal0 [0x005458AA+1333418]
	Ordinal0 [0x00554F38+1396536]
	Ordinal0 [0x0054568B+1332875]
	Ordinal0 [0x005221D4+1188308]
	Ordinal0 [0x0052302F+1191983]
	GetHandleVerifier [0x007E67A6+1545030]
	GetHandleVerifier [0x0089105C+2243580]
	GetHandleVerifier [0x006EBC97+518199]
	GetHandleVerifier [0x006EAD80+514336]
	Ordinal0 [0x005FED2D+2092333]
	Ordinal0 [0x00602EE8+2109160]
	Ordinal0 [0x00603022+2109474]
	Ordinal0 [0x0060CB71+2149233]
	BaseThreadInitThunk [0x7602FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77547A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77547A6E+238]

<ipython-input-183-b1ecfbe3c8d3>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_charts=driver.find_element_by_xpath("//h3[@id='mega-menu-item-charts']/a")

In [184]:
#clicking on charts:
try:
    search_charts=driver.find_element_by_xpath("//h3[@id='mega-menu-item-charts']/a")
    search_charts.click()
except ElementNotInteractableException as e:
    print("Exception raised",e)

<ipython-input-184-d712522fe89e>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_charts=driver.find_element_by_xpath("//h3[@id='mega-menu-item-charts']/a")

In [185]:
#fetching hot 100 webpage
try:
    search_s=driver.find_element_by_xpath("//div[@class='u-flex-grow-0 lrv-u-text-align-center']/span/a")
    search_s.click()
except ElementNotInteractableException as e:
     driver.get("https://www.billboard.com/charts/hot-100/")

<ipython-input-185-38fcd2995b91>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_s=driver.find_element_by_xpath("//div[@class='u-flex-grow-0 lrv-u-text-align-center']/span/a")

In [203]:
#creating variables:
song_name=[]
artist_name=[]
last_week_rank=[]
peak_rank=[]
weeks_on_board=[]


#fetching song_name:
try:
    song_n=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/h3")
    for i in song_n:
        sn=i.text
        song_name.append(sn)
except NoSuchElementException:
    song_name.append('-')

#fetching artist_name:
try:
    artist_tags=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/span")
    for i in artist_tags:
        artists=i.text
        artist_name.append(artists)
except NoSuchElementException:
    artist_name.append('-')

# fetching last_week_rank:
try:
    lwr_tags=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/span")
    for i in lwr_tags:
        lwr_t=i.text
        last_week_rank.append(lwr_t)
except NoSuchElementException:
    last_week_rank.append('-')

#fetching peak_rank
try:
    pr_tags=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/span")
    for i in pr_tags:
        pr_t=i.text
        peak_rank.append(pr_t)
except NoSuchElementException:
    peak_rank.append('-')

#fetching weeks_on_board:
try:
    wob_tags=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/span")
    for i in wob_tags:
        wob_t=i.text
        weeks_on_board.append(wob_t)
except NoSuchElementException:
    weeks_on_board.append('-')

<ipython-input-203-5d492f198fb4>:11: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  song_n=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/h3")
<ipython-input-203-5d492f198fb4>:20: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  artist_tags=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/span")
<ipython-input-203-5d492f198fb4>:29: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  lwr_tags=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/span")
<ipython-input-203-5d492f198fb4>:38: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  pr_tags=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/span")
<ipython-input-203-5d492f198fb4>:47: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  wob_tags=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/span")

In [205]:
#creating dataframe:
billboardf=pd.DataFrame({' Song Name ':song_name,
                ' Artist Name ':artist_name[0:400:4],
                ' Last Week Rank ':last_week_rank[1:400:4],
                ' Peak Rank ':peak_rank[2:400:4],
                ' Weeks on Board ':weeks_on_board[3:400:4]})

In [206]:
billboardf

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks on Board
0,All I Want For Christmas Is You,Mariah Carey,2,1,49
1,Rockin' Around The Christmas Tree,Brenda Lee,3,2,43
2,Easy On Me,Adele,1,1,10
3,Jingle Bell Rock,Bobby Helms,6,3,40
4,A Holly Jolly Christmas,Burl Ives,5,4,24
...,...,...,...,...,...
95,No Love,Summer Walker & SZA,78,13,6
96,Bad Man (Smooth Criminal),Polo G,70,49,5
97,Feel Alone,Juice WRLD,-,98,1
98,Heart On Fire,Eric Church,95,89,4
99,Bubbly,Young Thug With Drake & Travis Scott,91,20,9

Q7.Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [164]:
#website url
driver.get("https://www.naukri.com/")

In [167]:
#fetching recruiter tab:

try:
    recruit_url=driver.find_element_by_xpath("//a[@title='Search Recruiters']")
    recruit_url.click()
except:
    print("fail")
time.sleep(1)

<ipython-input-167-e34bc5ad726d>:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  recruit_url=driver.find_element_by_xpath("//a[@title='Search Recruiters']")

In [170]:
#fetching recruiter webapage
driver.get("https://www.naukri.com/hr-recruiters-consultants")

#searhing Data Science
try:
    search_job=driver.find_element_by_xpath("//input[@class='sugInp']")
    search_job.send_keys("Data Science")
    time.sleep(2)
    search_c=driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")
    search_c.click()
except:
    pint('fail')

<ipython-input-170-4f55e4e10eba>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_job=driver.find_element_by_xpath("//input[@class='sugInp']")
<ipython-input-170-4f55e4e10eba>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_c=driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")

In [47]:
#creating variables:
Names=[]
Designations=[]
Companys=[]
Place=[]
Skill_set=[]

# fetching Name
try:
    Name_tags=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
    for i in Name_tags:
        names_t=i.text
        Names.append(names_t)
    Names[0:]
except NoSuchElementException:
    Names.append('-')
    
#fetching Designation
try:
    designation_tag=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
    for i in designation_tag:
        designation_t=i.text
        Designations.append(designation_t)
    Designations[0:]
except NoSuchElementException:
    Designations.append('-')
    
# fetching Company
try:
    company_tags=driver.find_elements_by_xpath("//a[@class='ellipsis'][2]")
    for i in company_tags:
        companys=i.text
        Companys.append(companys)
    Companys[0:]
except NoSuchElementException:
    Companys.append('-')
    
#fetching Place
try:
    place_t=driver.find_elements_by_xpath("//small[@class='ellipsis']")
    for i in place_t:
        places=i.text
        Place.append(places)
    Place[0:49]
except NoSuchElementException:
    Place.append('-')
    
# fetching Skill set
try:
    Skill_tag=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
    brand_n=[]
    for i in Skill_tag:
        skills=i.text
        Skill_set.append(skills)
    Skill_set[0:]
except NoSuchElementException:
    Skill_set.append('-')

<ipython-input-47-17eac178a2f5>:8: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Name_tags=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
<ipython-input-47-17eac178a2f5>:17: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  designation_tag=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
<ipython-input-47-17eac178a2f5>:27: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  company_tags=driver.find_elements_by_xpath("//a[@class='ellipsis'][2]")
<ipython-input-47-17eac178a2f5>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  place_t=driver.find_elements_by_xpath("//small[@class='ellipsis']")
<ipython-input-47-17eac178a2f5>:46: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Skill_tag=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")

In [48]:
#creating dataframe
naukridf=pd.DataFrame({'Names':Names[0:47],
                'Designations':Designations[0:47],
                'Companys':Companys[0:47],
                'Place':Place[0:47],
                'Skill_set':Skill_set[0:47]})

In [50]:
naukridf

,Names,Designations,Companys,Place,Skill_set
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
11,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
12,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
16,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
19,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
23,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,Delhi,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Hyderabad / Secunderabad,"Web Technologies, Project Management, Software..."
30,Avodha,Business Development Associate,Nikitha Palaparthi,Mysoru / Mysore,"Ethical Hacking, Security Operations Center, S..."
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Bengaluru / Bangalore,"Data Analytics, Managed Services, Team Leading..."
32,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
33,Dhruv Dev Dubey,Company Recruitment Head,Confidential,New Delhi,"Server Administartion, Verilog, Vhdl, Digital ..."
34,Amit Sharma,Consultant,ASCO consulting,Chennai,"Machine Learning, Artificial Intelligence, Dat..."
35,Kanan,senior technology instructor,NY INST,Aligarh,"C, C++, Artificial Intelligence, Python, Php, ..."
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Salt Lake City,"Relationship Management, Retail Sales, Private..."
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,Pune,"Data Science, Software Engineering"
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,Bengaluru / Bangalore,"Data Science, Big Data Analytics, Digital Mark..."
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Mumbai,"Data Science, Recruitment, Salary"
40,Ankit Sinha,Head Analytics,Suntech Global,Indore,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Bengaluru / Bangalore,"Software Development, Business Intelligence, B..."
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,MYSORE,"Data Science, Node.js, Angularjs"
43,Ashwini,Director Global Delivery,MRP Advisers,Hyderabad / Secunderabad,"Data Science, Media Marketing, Resource Planni..."
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Bengaluru / Bangalore,"Data Analysis, Learning, Data Science, Compute..."
45,Rajani Nagaraj,HR Manager,WildJasmine,Mumbai,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
46,ROHIT Kumar,Architect,LNT Private Limited,Hyderabad / Secunderabad,"Software Development, Core Java, Unit Testing,..."

Q8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [67]:
#fetching url:
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare")

In [64]:
#fetching variables:
Title_name=[]
Author_name=[]
Volume_sales=[]
Publisher=[]
Genre=[]


# fetching Title_name
try:
    Title_tags=driver.find_elements_by_xpath("//td[@class='left'][2]")
    for i in Title_tags:
        titles=i.text
        Title_name.append(titles)
    Title_name[0:]
except NoSuchElementException:
    Title_name.append('-')
    
#fetching Author_name
try:
    author_n=driver.find_elements_by_xpath("//td[@class='left'][3]")
    for i in author_n:
        authors=i.text
        Author_name.append(authors)
    Author_name[0:]
except NoSuchElementException:
    Author_name.append('-')
    
#fetching Volume_sales 
try:
    volume_tags=driver.find_elements_by_xpath("//td[@class='left'][4]")
    for i in volume_tags:
        volumes=i.text
        Volume_sales.append(volumes)
    Volume_sales[0:]
except NoSuchElementException:
    Volume_sales.append('-')
    
#fetching Publisher    
try:
    Publisher_tags=driver.find_elements_by_xpath("//td[@class='left'][5]")
    for i in Publisher_tags:
        p_t=i.text
        Publisher.append(p_t)
    Publisher[0:]
except NoSuchElementException:
    Publisher.append('-')
#fetching Genre    
try:
    genre_tags=driver.find_elements_by_xpath("//td[@class='last left']")
    for i in genre_tags:
        genres=i.text
        Genre.append(genres)
    Genre[0:]
except NoSuchElementException:
    Genre.append('-')

#creating dataframe:
book_df=pd.DataFrame({'Title name':Title_name,
                'Author name':Author_name,
                'Volume_sales':Volume_sales,
                'Publisher':Publisher,
                'Genre':Genre})

<ipython-input-64-f345741efd7b>:11: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Title_tags=driver.find_elements_by_xpath("//td[@class='left'][2]")
<ipython-input-64-f345741efd7b>:21: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  author_n=driver.find_elements_by_xpath("//td[@class='left'][3]")
<ipython-input-64-f345741efd7b>:31: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  volume_tags=driver.find_elements_by_xpath("//td[@class='left'][4]")
<ipython-input-64-f345741efd7b>:41: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Publisher_tags=driver.find_elements_by_xpath("//td[@class='left'][5]")
<ipython-input-64-f345741efd7b>:50: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  genre_tags=driver.find_elements_by_xpath("//td[@class='last left']")

In [65]:
book_df

,Title name,Author name,Volume_sales,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9.Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [77]:
#fetching url:
driver.get("https://www.imdb.com/list/ls095964455/")

In [93]:
#creating variables:

movie_name= []
year_span=[]
genre=[]
run_time=[]
rating=[]
votes=[]

#fetching movie_name:
try:
    movie_tag=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in movie_tag:
        movies=i.text
        movie_name.append(movies)
except NoSuchElementException as e:
    movie_name.append('-')
    
#fetching year_span:
try:
    years_tag=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in years_tag:
        years=i.text
        year_span.append(years)
except NoSuchElementException as e:
    year_span.append('-')
    
#fetching genre:
try:
    genre_tag=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genre_tag:
        genres=i.text
        genre.append(genres)
except NoSuchElementException as e:
    genre.append('-')
    
#fetching run_time:
try:
    run_tag=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in run_tag:
        runs=i.text
        run_time.append(runs)
except NoSuchElementException as e:
    run_time.append('-')
    
#fetching rating:
try:
    rating_tag=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in rating_tag:
        ratings=i.text
        rating.append(ratings)
except NoSuchElementException as e:
    rating.append('-')
    
#fetching votes:
try:
    votes_tag=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in votes_tag:
        vote=i.text
        votes.append(vote)
except NoSuchElementException as e:
    votes.append('-')

# creating DataFrame
moviedf=pd.DataFrame({'Movie name':movie_name,
                'Year Span':year_span,
                'Genre':genre,
                'Run Time':run_time,
                'Rating':rating,
                'Votes':votes})

<ipython-input-93-84c478c80a64>:12: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  movie_tag=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
<ipython-input-93-84c478c80a64>:21: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  years_tag=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
<ipython-input-93-84c478c80a64>:30: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  genre_tag=driver.find_elements_by_xpath("//span[@class='genre']")
<ipython-input-93-84c478c80a64>:39: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  run_tag=driver.find_elements_by_xpath("//span[@class='runtime']")
<ipython-input-93-84c478c80a64>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  rating_tag=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
<ipython-input-93-84c478c80a64>:57: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  votes_tag=driver.find_elements_by_xpath("//span[@name='nv']")

In [94]:
moviedf

,Movie name,Year Span,Genre,Run Time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,920,548"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"945,078"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"918,891"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"275,142"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"235,497"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"46,928"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,722"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"182,045"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"38,058"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"216,342"

Q10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [117]:
#fetching url:
driver.get("https://archive.ics.uci.edu/ml/index.php")

In [118]:
time.sleep(2)

# Clicking on Showalldataset 
try:
    depository_button=driver.find_element_by_xpath("//td[@valign='top'][1]/span[2]")
    depository_button.click()
except ElementNotInteractableException as ed:
    print('Exception raised')

<ipython-input-118-3395855216a6>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  depository_button=driver.find_element_by_xpath("//td[@valign='top'][1]/span[2]")

In [119]:
#creating variable:

Dataset_name=[]
Data_type=[]
Task=[]
Attribute_type=[]
No_of_instances=[]
No_of_attribute=[]
Yearz=[]

time.sleep(2)

#fetching Dataset_name:
try:
    Dataset_tag=driver.find_elements_by_xpath("//p[@class='normal']")
    for i in Dataset_tag:
        datasetz=i.text
        Dataset_name.append(datasetz)
except NoSuchElementException as e:
    Dataset_name.append('-')
    time.sleep(2)
    
#fetching Data_type:
try:
    data_tag=driver.find_elements_by_xpath("//p[@class='normal']")
    for i in data_tag:
        datas=i.text
        Data_type.append(datas)
except NoSuchElementException as e:
    Data_type.append('-')

#fetching Task:
try:
    Task_tag=driver.find_elements_by_xpath("//p[@class='normal']")
    for i in Task_tag:
        tasks=i.text
        Task.append(tasks)
except NoSuchElementException as e:
    Task.append('-')

#fetching Attribute_type:
try:
    Attribute_tag=driver.find_elements_by_xpath("//p[@class='normal']")
    for i in Attribute_tag:
        att=i.text
        Attribute_type.append(att)
except NoSuchElementException as e:
    Attribute_type.append('-')
    
#fetching No_of_instances:
try:
    instances_tag=driver.find_elements_by_xpath("//p[@class='normal']")
    for i in instances_tag:
        instances=i.text
        No_of_instances.append(instances)
except NoSuchElementException as e:
    No_of_instances.append('-')
    
#fetching No_of_attribute:
try:
    na_tag=driver.find_elements_by_xpath("//p[@class='normal']")
    for i in na_tag:
        noa=i.text
        No_of_attribute.append(noa)
except NoSuchElementException as e:
    No_of_attribute.append('-')
    
#fetching Yearz:
try:
    Yearz_tag=driver.find_elements_by_xpath("//p[@class='normal']")
    for i in Yearz_tag:
        Yearzs=i.text
        Yearz.append(Yearzs)
except NoSuchElementException as e:
    Yearz.append('-')

<ipython-input-119-4b9e41b32162>:12: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Dataset_tag=driver.find_elements_by_xpath("//p[@class='normal']")
<ipython-input-119-4b9e41b32162>:22: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  data_tag=driver.find_elements_by_xpath("//p[@class='normal']")
<ipython-input-119-4b9e41b32162>:31: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Task_tag=driver.find_elements_by_xpath("//p[@class='normal']")
<ipython-input-119-4b9e41b32162>:40: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Attribute_tag=driver.find_elements_by_xpath("//p[@class='normal']")
<ipython-input-119-4b9e41b32162>:49: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  instances_tag=driver.find_elements_by_xpath("//p[@class='normal']")
<ipython-input-119-4b9e41b32162>:58: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  na_tag=driver.find_elements_by_xpath("//p[@class='normal']")
<ipython-input-119-4b9e41b32162>:67: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Yearz_tag=driver.find_elements_by_xpath("//p[@class='normal']")

In [146]:
#creating dataframe:
statsdf=pd.DataFrame({'Dataset Name':Dataset_name[8:4356:7],'Data Type':Data_type[9:4357:7],
                'Task':Task[10:4364:7],
                'Attribute type':Attribute_type[11:4364:7],
                'No of Instances':No_of_instances[12:4364:7],
                'No of Attribute':No_of_attribute[13:4364:7],
                'Year':Yearz[14:4364:7]})

In [147]:
statsdf

,Dataset Name,Data Type,Task,Attribute type,No of Instances,No of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021